PKG_NAME=cayenne-lpp
PKG_URL=https://github.com/aabadie/cayenne-lpp
PKG_VERSION=ad3aa26043e221eda28ac3da2484e1ef84986442
PKG_LICENSE=LGPLv2.1

include $(RIOTBASE)/pkg/pkg.mk

all:
	$(QQ)"$(MAKE)" -C $(PKG_SOURCE_DIR) -f $(RIOTBASE)/Makefile.base
